In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv("/Iris.csv")
x=dataset[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=dataset['Species']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.35)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gmodel=GaussianNB()
gmodel.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
gpred=gmodel.predict(xtest)
from sklearn.metrics import confusion_matrix
gcm=confusion_matrix(ytest,gpred)
print(gcm)

[[14  0  0]
 [ 0 16  1]
 [ 0  2 20]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,gpred)

0.9433962264150944

In [ ]:
print("Probabilities of falling into each class")
print(gmodel.predict_proba([[5,3,1.2,2]]))
print("Input is classified into")
ans=gmodel.predict([[5,3,1.2,2]])
print(ans)

Probabilities of falling into each class
[[6.81006132e-287 2.50932370e-022 1.00000000e+000]]
Input is classified into
['Iris-virginica']
