In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [ ]:
iris = pd.read_csv("/content/Iris (1).csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris.shape

(150, 6)

In [ ]:
iris["Species"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object>

In [ ]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
iris.describe(include="all")

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
count   150.000000     150.000000    150.000000     150.000000    150.000000   
unique         NaN            NaN           NaN            NaN           NaN   
top            NaN            NaN           NaN            NaN           NaN   
freq           NaN            NaN           NaN            NaN           NaN   
mean     75.500000       5.843333      3.054000       3.758667      1.198667   
std      43.445368       0.828066      0.433594       1.764420      0.763161   
min       1.000000       4.300000      2.000000       1.000000      0.100000   
25%      38.250000       5.100000      2.800000       1.600000      0.300000   
50%      75.500000       5.800000      3.000000       4.350000      1.300000   
75%     112.750000       6.400000      3.300000       5.100000      1.800000   
max     150.000000       7.900000      4.400000       6.900000      2.500000   

            Species  
count           150  
unique            3  
top     Iris-setosa  
freq             50  
mean            NaN  
std             NaN  
min             NaN  
25%             NaN  
50%             NaN  
75%             NaN  
max             NaN

In [ ]:
X = iris.iloc[:,:4]
X.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1           3.5            1.4
1   2            4.9           3.0            1.4
2   3            4.7           3.2            1.3
3   4            4.6           3.1            1.5
4   5            5.0           3.6            1.4

In [ ]:
Y = iris.iloc[:,-1]
Y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [ ]:
X = preprocessing.StandardScaler().fit_transform(X)
X[0:4]

array([[-1.72054204, -0.90068117,  1.03205722, -1.3412724 ],
       [-1.69744751, -1.14301691, -0.1249576 , -1.3412724 ],
       [-1.67435299, -1.38535265,  0.33784833, -1.39813811],
       [-1.65125846, -1.50652052,  0.10644536, -1.2844067 ]])

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)
Y_test.shape

(45,)

In [ ]:
knnmodel = KNeighborsClassifier(n_neighbors=3)
knnmodel.fit(X_train,Y_train)
Y_predict = knnmodel.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
acc = accuracy_score(Y_test,Y_predict)

In [ ]:
acc

1.0

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test.values,Y_predict)
cm

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]])

In [ ]:
cm1 = pd.DataFrame(data=cm, index=["setosa","versicolor","virginica"])
cm1

0   1   2
setosa      16   0   0
versicolor   0  18   0
virginica    0   0  11

In [ ]:
prediction_output=pd.DataFrame(data=[Y_test.values,Y_predict],index=["Y_test.values","Y_predict"])
prediction_output.transpose()

Y_test.values        Y_predict
0    Iris-virginica   Iris-virginica
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6       Iris-setosa      Iris-setosa
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11  Iris-versicolor  Iris-versicolor
12  Iris-versicolor  Iris-versicolor
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29      Iris-setosa      Iris-setosa
30   Iris-virginica   Iris-virginica
31  Iris-versicolor  Iris-versicolor
32      Iris-setosa      Iris-setosa
33   Iris-virginica   Iris-virginica
34   Iris-virginica   Iris-virginica
35  Iris-versicolor  Iris-versicolor
36      Iris-setosa      Iris-setosa
37  Iris-versicolor  Iris-versicolor
38  Iris-versicolor  Iris-versicolor
39  Iris-versicolor  Iris-versicolor
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42   Iris-virginica   Iris-virginica
43      Iris-setosa      Iris-setosa
44      Iris-setosa      Iris-setosa

In [ ]:
prediction_output.iloc[0,:].value_counts()

Iris-versicolor    18
Iris-setosa        16
Iris-virginica     11
Name: Y_test.values, dtype: int64

In [ ]:
Ks = 20
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))

In [ ]:
mean_acc

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [ ]:
std_acc


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])